# Generated by Django 4.0.4 on 2022-05-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_plate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileforrecognition',
            options={'verbose_name': 'Загруженный файл', 'verbose_name_plural': 'Загруженные файлы'},
        ),
    ]
