# Generated by Django 4.0.4 on 2022-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_plate', '0002_alter_fileforrecognition_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileforrecognition',
            name='file',
            field=models.FileField(upload_to='test/'),
        ),
    ]
