# Generated by Django 4.0.4 on 2022-05-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_plate', '0003_alter_fileforrecognition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileforrecognition',
            name='file',
        ),
        migrations.AddField(
            model_name='fileforrecognition',
            name='text',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
