# Generated by Django 4.0.4 on 2022-05-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_plate', '0004_remove_fileforrecognition_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileforrecognition',
            name='text',
        ),
        migrations.AddField(
            model_name='fileforrecognition',
            name='file',
            field=models.FileField(default=1, upload_to='test/'),
            preserve_default=False,
        ),
    ]
