# Generated by Django 4.0.4 on 2022-05-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_plate', '0005_remove_fileforrecognition_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileforrecognition',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='test/'),
        ),
    ]
