# Generated by Django 4.0.4 on 2022-05-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_plate', '0006_alter_fileforrecognition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileforrecognition',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='test/', verbose_name='Загруженный файл'),
        ),
    ]
